### ISSUE TITLE
Footer responsive alla. 

### ISSUE THREAD

**Issue by bonniesimon** [netxmace/NetX#21]

**Comment by thetronjohnson** [comment]
![Screenshot from 2020-09-16 23 49 08](https://user-images.githubusercontent.com/22194802/93376454-3dcf1680-f877-11ea-80c0-c660062d406c.jpeg)

Should we change the design of the footer? I do feel like that it doesn't match the rest of the design

**Comment by treezjoz** [comment]
Yup,It's not as cool as rest of the page. Can you please post it as another issue?
