### ISSUE TITLE
Sort Events in Events page by latest

### ISSUE THREAD

**Issue by bonniesimon** [netxmace/NetX#29]
Sort the events such that the latest event comes first.

**Comment by daedraMex** [comment]
I could help with this. But could you tag it with hacktoberfest?

**Comment by bonniesimon** [comment]
> 
> 
> I could help with this. But could you tag it with hacktoberfest?

Actually this repo is the website for our college's open source club. And we're trying to give chance for our juniors to do the issues. 
We'll be coming with a hacktoberfest event, and at that time we'll put out some issues specifically for hacktoberfest. 
Right now, I'm sorry but its club members only
